name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server:
    name: server (test/build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install (server)
        run: npm ci
        working-directory: server

      - name: Test (server)
        run: npm test --if-present
        working-directory: server

      - name: Build (server)
        run: npm run build --if-present
        working-directory: server

  client:
    name: client (test/build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install (client)
        run: npm ci
        working-directory: client

      - name: Test (client)
        run: npm test --if-present
        working-directory: client

      - name: Build (client)
        run: npm run build --if-present
        working-directory: client
